batch_size: 1
best_model_path: runs/baseline3/phase1_fine_tune/best_model.pth
class_names:
- l-pass
- r-pass
- l-spike
- r_spike
- l_set
- r_set
- l_winpoint
- r_winpoint
dataset_root: Projects/Vollyball/Volley dataset files
dataset_type: PersonActionDataset
device: cuda
learning_rate: 0.0001
lr_scheduler: true
mode: player_feature_extraction
num_epochs: 25
num_workers: 4
pin_memory: true
save_dir: ./runs/baseline3/phase2_feature_extraction/features
seed: 42
use_all_frames: true

