batch_size: 16
best_model_path: /runs/baseline4/best_model.pth
class_names:
- l-pass
- r-pass
- l-spike
- r_spike
- l_set
- r_set
- l_winpoint
- r_winpoint
dataset_root: Projects/Vollyball/Volley dataset files
dataset_type: GroupActivityDataset
device: cuda
hidden_size_frame: 1024
input_size: 2048
learning_rate: 0.0001
lr_scheduler: true
mix_up: false
mode: frame_feature_extraction
num_epochs: 25
num_workers: 0
patience: 5
pin_memory: true
save_dir: ./runs/baseline4
seed: 42
use_all_frames: true
